type-complexity-threshold = 999
too-many-arguments-threshold = 20
disallowed-methods = [
    # we use strict naming for pasta fields
    { path = "pasta_curves::Fp", reason = "use pasta_curves::pallas::Base or pasta_curves::vesta::Scalar instead to communicate your intent" },
    { path = "pasta_curves::Fq", reason = "use pasta_curves::pallas::Scalar or pasta_curves::vesta::Base instead to communicate your intent" },
]
