[package]
name = "fcomm"
version = "0.1.1"
authors = ["porcuquine <porcuquine@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Functional commitments with Lurk"
edition = "2021"
repository = "https://github.com/lurk-lab/lurk-rs"

[[bin]]
name = "fcomm"
path = "src/bin/fcomm.rs"

[dependencies]
base64 = "0.13.1"
bellperson = { git = "https://github.com/lurk-lab/bellperson", branch = "dev" }
blstrs = { git = "https://github.com/lurk-lab/blstrs", branch = "dev" }
clap = { version = "3.2", features = ["derive"] }
clap-verbosity-flag = "1.0"
ff = "0.13"
hex = { version = "0.4.3", features = ["serde"] }
log = "0.4.17"
libipld = { package = "lurk-ipld", version = "0.3.0", default-features = false, features = ["dag-cbor", "dag-json", "serde-codec"] }
lurk = { path = "../", package = "lurk" }
once_cell = "1.17.1"
pairing_lib = { version = "0.23", package = "pairing" }
pretty_env_logger = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
thiserror = "1.0.38"
pasta_curves = { git = "https://github.com/lurk-lab/pasta_curves", branch = "dev", features = ["repr-c", "serde"] }

[dev-dependencies]
assert_cmd = "2.0.8"
predicates = "2.1.5"
tempfile = "3.5.0"
num_cpus = "1.15.0"
camino = "1.1.4"
