[package]
name = "fcomm"
version = "0.1.0"
authors = ["porcuquine <porcuquine@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Functional commitments via Lurk"
edition = "2018"

[dependencies]
bellperson = { version = "0.18.0" }
blstrs = "0.4.1"
ff = "0.11.0"
log = "0.4.14"
lurk = { path = "../", package = "lurk" }
once_cell = "1.9.0"
pairing_lib = { version = "0.21", package = "pairing" }
pretty_env_logger = "0.4"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde-hex = { version = "0.1.0" }
structopt = { version = "0.3", default-features = false }

[dev-dependencies]
assert_cmd = "2.0.4"
predicates = "2.1.1"
tempdir = "0.3.7"

